name: pokemon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  sqflite: ^2.2.4+1
  path_provider: ^2.0.11
  connectivity_plus: ^3.0.2
  cached_network_image: ^3.2.3
  internet_connection_checker: ^1.0.0+1
  path: ^1.8.3
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png